#ifndef AUDIO_DATA_H
#define AUDIO_DATA_H

typedef enum {
    MOD_ACCESS = 0,    MOD_BALCONY,     MOD_BALROGTHEME, MOD_BREAKDOWN,
    MOD_CAVE,          MOD_CAVESTORY,   MOD_CHARGE,      MOD_GAMEOVER,
    MOD_GESTATION,     MOD_GETHEARTTANK,MOD_GOTITEM,      MOD_GRAVITY,
    MOD_HEROEND,       MOD_LASTBATTLE,  MOD_LASTCAVE,    MOD_MOONSONG,
    MOD_ONTOGRASSTOWN, MOD_OPPRESSION,  MOD_PULSE,       MOD_QUIET,
    MOD_RUN,           MOD_RUNNINGHELL, MOD_SCORCHINGBACK,MOD_SEALCHAMBER,
    MOD_THEWAYBACKHOME,MOD_TYRANT,      MOD_VICTORY,     MOD_VIVI,
    MOD_WANPAK2,       MOD_WHATISLOVEE, MOD_WHATISLOVE,  MOD_ZOMBIE,
    MOD_COUNT
} MusicId;

void play_music_track(MusicId id);

#endif
